version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    env_file: ./.env
    environment:
        - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
        - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
        - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
    logging:
        options:
            max-size: 1g
    volumes:
      - ./db:/data/db
      - ./scripts/init.mongo.js:/docker-entrypoint-initdb.d/init.mongo.js:ro

  app:
    depends_on:
      - mongo
    restart: on-failure
    env_file: ./.env
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_HOST=mongo
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    links: 
        - mongo
    volumes:
      - ./server:/app/server

volumes:
  db:
